### ISSUE TITLE
Could not find BTDF MSI to download anywhere

### ISSUE THREAD

**Issue by vikas15bhardwaj** [BTDF/DeploymentFramework#437]
Not sure where is MSI download of BTDF now, it used to be on codeplex and its not there.

**Comment by billchesnut** [comment]
Github

Bill Chesnut - +61 404 063 648
________________________________

**Comment by vikas15bhardwaj** [comment]
can you provide the link, on GitHub there is only source code I see

**Comment by tfabraham** [comment]
The latest release is on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=DeployFxForBizTalkTeam.DeploymentFrameworkforBizTalk).

The Visual Studio extensions are available on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/search?term=publisher%3A%22Deployment%20Framework%20for%20BizTalk%20Team%22&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance) and through the Visual Studio extensions dialog box.

And, all releases are available [here](https://github.com/BTDF/DeploymentFramework/releases)

Tom
