### ISSUE TITLE
RadioButtons ValueType of SetEnvUIConfig.xsd is limited to only 5

### ISSUE THREAD

**Issue by Aravindhrk** [BTDF/DeploymentFramework#448]
We are in need of having more than 5 environments, and we would like to have RadioButton instead of Fileselect.

We are using Deployment framework V5.5 

is it possible to achieve this?

**Comment by tfabraham** [comment]
You could create a custom version of SetEnvUI.exe.  The code that sets up the radio button controls and the overall UI is [here](https://github.com/BTDF/DeploymentFramework/blob/master/src/Tools/SetEnvUI/SetEnvUI.cs).

**Comment by Aravindhrk** [comment]
Thank you...
