### ISSUE TITLE
BTDF v5.7 deploy issues with IIS artifacts 

### ISSUE THREAD

**Issue by SilamG** [BTDF/DeploymentFramework#462]
When i deploy the IIS artificats with btdf , the artifacts doesnt seems to deploy properly as said in the documentation. Below is my code and my findings 

```
<ItemGroup>
    <IISAppPool Include="MyBiztalkServiceAppPool" Condition="'$(Configuration)' != 'Server'">
      <DeployAction>CreateOrUpdate</DeployAction>
      <DotNetFrameworkVersion>v4.0</DotNetFrameworkVersion>
      <IdentityType>SpecificUser</IdentityType>
      <UserName>${VDIR_UserName}</UserName>
      <Password>${VDIR_UserPass}</Password>
      <PipelineMode>Integrated</PipelineMode>
      <UndeployAction>Delete</UndeployAction>
    </IISAppPool>
 </ItemGroup>

 <ItemGroup>
    <IISApp Include="MyBiztalkService" >
      <AppPoolName>MyBiztalkServiceAppPool</AppPoolName>
      <DeployAction>CreateOrUpdate</DeployAction>
      <SiteName>Default Web Site</SiteName>
      <PhysicalPath>..\SolutionItems\WebServices\MyBiztalkService</PhysicalPath>
      <VirtualPath>/MyBiztalkService</VirtualPath>      
      <UndeployAction>Delete</UndeployAction>
    </IISApp>
  </ItemGroup>

```

1. The Web-service contents folder are not getting copied to the right folder structure. for instance the webservices source code is under solutionItems\Webservices\MyBiztalkService folder but when the msi gets deployed to the target machine, the webservice is directly getting copied to the root folder. Even though in IIS, the application is created, the contents are still missing due to invalid path.

2.The Authentication is not getting properly configured as in the web.config file. While the webservice is configured for basic authentication, Btdf deploys as Windows and Anonymous enabled.

3. The AppPool is deployed in classic mode though Integrated is specified.

4. the AppPool does not replace the username and password from the settings file. It replaces it as string literal.

thank you for your wonderful support to the developer community and hope these issues are fixed.

**Comment by tfabraham** [comment]
Please review in detail the IIS sample application which is installed with BTDF and available [here](https://github.com/BTDF/DeploymentFramework/tree/master/src/Samples/BizTalk/IIS).

You can set the values of VDIR_UserName and VDIR_UserPass via the wizard UI (InstallWizard.xml), or put them in the environment settings spreadsheet and reference them in the property PropsFromEnvSettings.

BTDF does not support configuration of the IIS vdir authentication mode, but you can include that as a custom step that calls out to appcmd.exe.
