### ISSUE TITLE
Unable to deploy the MSI generated via TFS Buid Definition

### ISSUE THREAD

**Issue by gaurav-p-sood** [BTDF/DeploymentFramework#476]
Hi

I am unable to deploy the MSI when run as admin. 

The MSI has been generated by building BTDF project via TFS 2017 build definition . Following is the error that I receive after selecting the Binding file i the wizard. 

**C:\Program Files (x86)\ProjectName\1.0.0.0\Deployment\Framework\BizTalkDeploymentFramework.targets(1782,3): error MSB4067: The element <ItemDefinitionGroup> beneath element <Project> is unrecognized.**

Also I know the VS tools for 2019 are yet to be released , is there any way to add new Deployment project to the new solution that do not have BTDF project yet . BTDF project template does not appear under "Add new Project " window.

Regards
Gaurav

**Comment by gaurav-p-sood** [comment]
> Hi
> 
> I am unable to deploy the MSI when run as admin.
> 
> The MSI has been generated by building BTDF project via TFS 2017 build definition . Following is the error that I receive after selecting the Binding file i the wizard.
> 
> **C:\Program Files (x86)\ProjectName\1.0.0.0\Deployment\Framework\BizTalkDeploymentFramework.targets(1782,3): error MSB4067: The element beneath element is unrecognized.**
> 
> Also I know the VS tools for 2019 are yet to be released , is there any way to add new Deployment project to the new solution that do not have BTDF project yet . BTDF project template does not appear under "Add new Project " window.
> 
> Regards
> Gaurav

When traversed to Line 1782,3 under .target file , this is element group found. 

<ItemDefinitionGroup>
    <IISAppPool>
      <DotNetFrameworkVersion>v4.0</DotNetFrameworkVersion>
      <PipelineMode>Integrated</PipelineMode>
      <Enable32Bit>False</Enable32Bit>
      <IdentityType>ApplicationPoolIdentity</IdentityType>
      <DeployAction>$(IISAppPoolDefaultDeployAction)</DeployAction>
      <UndeployAction>$(IISAppPoolDefaultUndeployAction)</UndeployAction>
    </IISAppPool>
  </ItemDefinitionGroup>


Regards
Gaurav

**Comment by tfabraham** [comment]
Hi Gaurav,

I often just copy the Deployment folder from an existing BizTalk project rather than re-create it through the wizard. You can also go to the Deployment Framework for BizTalk folder in Program Files (x86) and look in the Developer subfolder. The template project files used by the wizard are stored in a subfolder of Developer.

As to the error, my first guess is that you've got a syntax issue somewhere in your project's IIS elements. I'd try commenting out your IIS config and see if the problem clears up. If so, add things back until you can narrow down the problem.

Thanks,
Tom

**Comment by gaurav-p-sood** [comment]
Hi Tom

Thank you for your reply. 

Yesterday while working, when I used a different TEST machine to install the same MSI (the one that didn't install on my Dev machine) it worked flawlessly. 

Apparently it looks like machine has a issue with BTDF installation.

AGAIN many Thanks! for your quick updates on BTDF and making our lives easier. 

Cheers
Gaurav

**Comment by tfabraham** [comment]
You're welcome -- glad to hear it's working! Thanks for the update.
