### ISSUE TITLE
5.7.0 BizTalk 2016 Visual Studio 2015 Properties for MSI Installer 

### ISSUE THREAD

**Issue by verzada** [BTDF/DeploymentFramework#481]
I'm trying to figure how to install the BizTalk Deployment Framework 5.7.0 from commandline for Visual Studio 2015. but I have no idea how to do it.

Ideally something like 
```
msiexec /a /visualstudio2015  DeploymentFrameworkForBizTalkV5_7.msi
```

If i run
```
msiexec /a DeploymentFrameworkForBizTalkV5_7.msi
```
the installer will not install anything 

Though I've found the following properties; but I have no idea how to use any of them except for ALLUSERS.
According to the log, I can create using the command

```
msiexec /lp! msilog.log /i DeploymentFrameworkForBizTalkV5_7.msi
``` 
most of these properties are environmental properties and has nothing to do with initializing the installation of a given Visual Studio setup.

ALLUSERS
BTS_PRODUCTNAME
ESBTOOLKIT21_DIR
ESBTOOLKIT22_DIR
ESBTOOLKIT23_DIR
ESBTOOLKIT24_DIR
VS2010_IDE_VCSHARP_PROJECTSYSTEM_INSTALLED
VS2010_SCHEMAS_DIR
VS2010DEVENV
VS2012_EXTENSIONS_DIR
VS2012_IDE_VCSHARP_PROJECTSYSTEM_INSTALLED
VS2012_SCHEMAS_DIR
VS2012DEVENV
VS2013_EXTENSIONS_DIR
VS2013_IDE_VCSHARP_PROJECTSYSTEM_INSTALLED
VS2013_SCHEMAS_DIR
VS2013DEVENV
VS2015_EXTENSIONS_DIR
VS2015_IDE_VCSHARP_PROJECTSYSTEM_INSTALLED
VS2015_SCHEMAS_DIR
VS2015DEVENV

**Comment by tfabraham** [comment]
Hello,
If you're trying to do it on a developer machine with Visual Studio 2015 installed, I'd try something like this:

`msiexec /i DeploymentFrameworkForBizTalkV5_7.msi ADDLOCAL=RuntimeFeature,DevToolsFeature,VS2015IntegrationFeature`

You could also try INSTALLLEVEL=1 in place of the ADDLOCAL=.. parameter.

**Comment by verzada** [comment]
Yep, that's correct. It's a Developer machine with Visual Studio 2015.
I'll uninstall the msi and see what happens when I run the command :)

**Comment by verzada** [comment]
Tried 

```
msiexec /i DeploymentFrameworkForBizTalkV5_7.msi ADDLOCAL=RuntimeFeature,DevToolsFeature,VS2015IntegrationFeature
```

Thought the installer wouldn't pop up but, it came up anyway

I think you need to add /quiet for it to be completely silent.

**Comment by tfabraham** [comment]
Did the second one with /quiet work as expected?

**Comment by verzada** [comment]
Absolutely :)
