### ISSUE TITLE
 CustomPostDeployTarget Runs before StartApplication

### ISSUE THREAD

**Issue by shumaila1993** [BTDF/DeploymentFramework#483]
As per Biztalk Deployment Framework : CustomPostDeployTarget Runs just after the Deployment Framework has deployed all artifacts and started the BizTalk application and just before the BizTalk hosts are restarted.

So in order to unenlist some sendports after 'StartApplication' I have added this target which execute a powershellScript and working fine.But why does VStudio execute target before starting the application.Can someone help?

**Comment by shumaila1993** [comment]
I am already using CustomPostDeployTarget .
________________________________

**Comment by tfabraham** [comment]
Sorry about that - I corrected my reply above.
