### ISSUE TITLE
BTDF 5.8 for Biztalk 2020 keeps using MSBUILD 2.0?

### ISSUE THREAD

**Issue by fabsenet** [BTDF/DeploymentFramework#484]
Hi,

I have a solution building on the current stack: biztalk 2020, windows 2019, btdf 5.8rc1, .net 4.8

When I try to run quick deploy on the biztalk server, it comes up with running msbuild 2.0. 

![image](https://user-images.githubusercontent.com/2065705/142624218-7fade077-6815-4af8-9a1d-f3cc0267ebae.png)

as my `<project>` tag, I already tried adding `ToolsVersion="4.0"` but without any change so far. it is now again just:

`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="ZesChecks" DefaultTargets="Installer">
`

The arguments of the quick deploy shortcut is `"C:\Windows\Microsoft.NET\Framework\v4.0.30319\\MSBuild.exe" "/p:Configuration=Server /t:LaunchServerDeployWizard ZES.Deployment.btdfproj /tv:4.0"`

So it seems, at least the build and install of the msi where correct as this path and version seems to be correct for me.

This is a migrated version from an earlier biztalk version, so I most probably messed up somewhere, any pointers?

**Comment by tfabraham** [comment]
Hello - you may be seeing the same thing as issue #478, which is an issue in v5.8 beta. Please look that over and see if it helps.

Thanks,
Tom

**Comment by fabsenet** [comment]
Ah thanks for your quick reply!

I could verify that changing the SetToolsVersionParam as stated in #478 works!

But I did not wanted to change them permanently, so I added instead the following target to my btdf file to fix the value:

```xml
  <Target Name="ReSetToolsVersionParam" AfterTargets="SetToolsVersionParam">
    <!-- Clamp tools version to 4 as this is the only one available vial .net framework 4.x without installing visual studio or anything -->
    <CreateProperty Value="/tv:4.0">
      <Output TaskParameter="Value" PropertyName="ToolsVersionParam" />
    </CreateProperty>
  </Target>
```
This works with the unmodified SetToolsVersionParam-Target!
