### ISSUE TITLE
How to find and uninstall this DeploymentFrameworkForBizTalkToolsForVS2015.vsix file in order to re-install it?

### ISSUE THREAD

**Issue by dexgu101** [BTDF/DeploymentFramework#490]
Installed DeploymentFrameworkForBizTalkV5_7.msi and DeploymentFrameworkForBizTalkToolsForVS2015.vsix. 
It does not show under the Tools of Visual Studio 2015, 
I reinstall this vsix file and get error: The extension is already installed to all applicable products. 

How to find and uninstall this vsix file in order to re-install them?

**Comment by tfabraham** [comment]
Once installed, the extension appears both in the Visual Studio Extension Manager and in the Help/About list of installed products.

**Comment by dexgu101** [comment]
Thanks for your quickly reply and really appreciate it. I have installed BTDF many times before and it's the first  time met such issue.
The Deployment Framework for BizTalk 5.7 can only be found in Programs and Features under Control panel, BTDF does not show up at visual studio 2015( see below for the list of installed product in VS2015). I tried to re-install the msi and vsix. The issue is when running DeploymentFrameworkForBizTalkToolsForVS2015.vsix and got "The extension is already installed to all applicable products". It was stuck there, cannot move on and need guide on how to solve it.

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA276
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-80000-00000-AA276
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-80000-00000-AA276
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA276
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA276
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft BizTalk Server 2016   08354-270-5270867-04121
Microsoft BizTalk Server 2016

Microsoft Team Foundation Server 2015 Power Tools   14.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

Microsoft.ServiceModel.Channels.MapperItem   1.0
Package to add the mapper activity to the WF toolbox

Microsoft® Host Integration Server 2016   
Microsoft® Host Integration Server 2016

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

PublishCommand Extension   1.0
PublishCommand Visual Stuido Extension Detailed Info

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by dexgu101** [comment]
This problem has been found and solved: 
The vsix file cannot be run with admin account(except with command), I login windows with a regular account and so the deployment framework was installed in VS but only visible when open VS with regular account. Therefore an admin account must be used to login windows and install this vsix file, in my case, only admin account has permission to deploy in vs.
Thank you,

**Comment by tfabraham** [comment]
That makes sense. I'm glad you found the solution! Thanks for posting the fix for others to reference in the future.
